[package]
name = "imu_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
awkernel_async_lib = { path = "../awkernel_async_lib", default-features = false }
awkernel_lib = { path = "../awkernel_lib", default-features = false } 